# Generated by Django 4.2.6 on 2023-10-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='receipe_folder'),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_name',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
